name: deployment
on:
  workflow_dispatch:
    inputs:
      app:
        description: 'The service to deploy'
        required: true
        default: 'woop'
        type: choice
        options:
        - woop
        - html 
jobs:
  woop:
    if : ${{ github.event.inputs.app == 'woop' }}
    runs-on: woop
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          docker network create --driver bridge my-network || true
          docker image prune -f
          docker build -t woop .
          containers=$(docker ps -q --filter "ancestor=woop")
          if [[ -n "$containers" ]]; then
            docker stop $containers
            docker rm $containers
          fi
          docker run -d -p 80:80 --name woop --network my-network woop
  html:
    if : ${{ github.event.inputs.app == 'html' }}
    runs-on: woop
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          docker build -t woop .
          rm -rf /home/opc/nginx/html/woop
          mkdir -p /home/opc/nginx/html/woop
          docker cp woop:/usr/share/nginx/html /home/opc/nginx/html/woop

